// Setup Action Types
export const FETCH_SETUP_REQUEST = 'FETCH_SETUP_REQUEST';
export const FETCH_SETUP_SUCCESS = 'FETCH_SETUP_SUCCESS';
export const FETCH_SETUP_FAILURE = 'FETCH_SETUP_FAILURE';
export const UPDATE_SETUP = 'UPDATE_SETUP';