// Setup Action Types
export const FETCH_SETUP_REQUEST = 'FETCH_SETUP_REQUEST';
export const FETCH_SETUP_SUCCESS = 'FETCH_SETUP_SUCCESS';
export const FETCH_SETUP_FAILURE = 'FETCH_SETUP_FAILURE';
export const UPDATE_SETUP = 'UPDATE_SETUP';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const SET_LOADING = 'SET_LOADING'

export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const CHECK_INVITATION_REQUEST = 'CHECK_INVITATION_REQUEST';
export const CHECK_INVITATION_SUCCESS = 'CHECK_INVITATION_SUCCESS';
export const CHECK_INVITATION_FAILURE = 'CHECK_INVITATION_FAILURE';
export const UPDATE_INVITATION = 'UPDATE_INVITATION';

export const CREATE_BATCH_REQUEST = 'CREATE_BATCH_REQUEST';
export const CREATE_BATCH_SUCCESS = 'CREATE_BATCH_SUCCESS';
export const CREATE_BATCH_FAILURE = 'CREATE_BATCH_FAILURE';
export const UPDATE_BATCH_TITLE_REQUEST = 'UPDATE_BATCH_TITLE_REQUEST';
export const UPDATE_BATCH_TITLE_SUCCESS = 'UPDATE_BATCH_TITLE_SUCCESS';
export const UPDATE_BATCH_TITLE_FAILURE = 'UPDATE_BATCH_TITLE_FAILURE';
export const RESET_INVITATION_REQUEST = 'RESET_INVITATION_REQUEST';
export const RESET_INVITATION_SUCCESS = 'RESET_INVITATION_SUCCESS';
export const RESET_INVITATION_FAILURE = 'RESET_INVITATION_FAILURE';
export const GET_ALL_BATCHES_REQUEST = 'GET_ALL_BATCHES_REQUEST';
export const GET_ALL_BATCHES_SUCCESS = 'GET_ALL_BATCHES_SUCCESS';
export const GET_ALL_BATCHES_FAILURE = 'GET_ALL_BATCHES_FAILURE';
export const GET_ALL_INVITATIONS_BY_BATCH_REQUEST = 'GET_ALL_INVITATIONS_BY_BATCH_REQUEST';
export const GET_ALL_INVITATIONS_BY_BATCH_SUCCESS = 'GET_ALL_INVITATIONS_BY_BATCH_SUCCESS';
export const GET_ALL_INVITATIONS_BY_BATCH_FAILURE = 'GET_ALL_INVITATIONS_BY_BATCH_FAILURE';
export const ADD_INVITATIONS_REQUEST = 'ADD_INVITATIONS_REQUEST';
export const ADD_INVITATIONS_SUCCESS = 'ADD_INVITATIONS_SUCCESS';
export const ADD_INVITATIONS_FAILURE = 'ADD_INVITATIONS_FAILURE';

export const AUTH_USER_SET = 'AUTH_USER_SET';
export const AUTH_USER_CLEARED = 'AUTH_USER_CLEARED';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const UPDATE_USER = 'UPDATE_USER';
export const ADD_PROFILE_TO_USER = 'ADD_PROFILE_TO_USER';
export const SET_ACTIVE_PROFILE = 'SET_ACTIVE_PROFILE';
export const REDIRECT_USER_REQUEST = 'REDIRECT_USER_REQUEST'
export const REDIRECT_USER_SUCCESS = 'REDIRECT_USER_SUCCESS'
export const REDIRECT_USER_FAILURE = 'REDIRECT_USER_FAILURE'

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
export const FETCH_SELECTED_USER_REQUEST = 'FETCH_SELECTED_USER_REQUEST';
export const FETCH_SELECTED_USER_SUCCESS = 'FETCH_SELECTED_USER_SUCCESS';
export const FETCH_SELECTED_USER_FAILURE = 'FETCH_SELECTED_USER_FAILURE';

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE';
export const SAVE_PROFILE_REQUEST = 'SAVE_PROFILE_REQUEST';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAILURE = 'SAVE_PROFILE_FAILURE';
export const UPDATE_BASIC_INFO_REQUEST = 'UPDATE_BASIC_INFO_REQUEST';
export const UPDATE_BASIC_INFO_SUCCESS = 'UPDATE_BASIC_INFO_SUCCESS';
export const UPDATE_BASIC_INFO_FAILURE = 'UPDATE_BASIC_INFO_FAILURE';
export const UPDATE_ABOUT_REQUEST = 'UPDATE_ABOUT_REQUEST';
export const UPDATE_ABOUT_SUCCESS = 'UPDATE_ABOUT_SUCCESS';
export const UPDATE_ABOUT_FAILURE = 'UPDATE_ABOUT_FAILURE';
export const UPDATE_THEME_REQUEST = 'UPDATE_THEME_REQUEST';
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS';
export const UPDATE_THEME_FAILURE = 'UPDATE_THEME_FAILURE';
export const UPDATE_COVER_IMAGE_REQUEST = 'UPDATE_COVER_IMAGE_REQUEST';
export const UPDATE_COVER_IMAGE_SUCCESS = 'UPDATE_COVER_IMAGE_SUCCESS';
export const UPDATE_COVER_IMAGE_FAILURE = 'UPDATE_COVER_IMAGE_FAILURE';
export const UPDATE_PROFILE_IMAGE_REQUEST = 'UPDATE_PROFILE_IMAGE_REQUEST';
export const UPDATE_PROFILE_IMAGE_SUCCESS = 'UPDATE_PROFILE_IMAGE_SUCCESS';
export const UPDATE_PROFILE_IMAGE_FAILURE = 'UPDATE_PROFILE_IMAGE_FAILURE';
export const UPDATE_LINKS_REQUEST = 'UPDATE_LINKS_REQUEST';
export const UPDATE_LINKS_SUCCESS = 'UPDATE_LINKS_SUCCESS';
export const UPDATE_LINKS_FAILURE = 'UPDATE_LINKS_FAILURE';
export const UPDATE_CONTACT_FORM_REQUEST = 'UPDATE_CONTACT_FORM_REQUEST';
export const UPDATE_CONTACT_FORM_SUCCESS = 'UPDATE_CONTACT_FORM_SUCCESS';
export const UPDATE_CONTACT_FORM_FAILURE = 'UPDATE_CONTACT_FORM_FAILURE';

export const FETCH_USER_BY_PROFILE_SUFFIX_REQUEST = 'FETCH_USER_BY_PROFILE_SUFFIX_REQUEST'
export const FETCH_USER_BY_PROFILE_SUFFIX_SUCCESS = 'FETCH_USER_BY_PROFILE_SUFFIX_SUCCESS'
export const FETCH_USER_BY_PROFILE_SUFFIX_FAILURE = 'FETCH_USER_BY_PROFILE_SUFFIX_FAILURE'

export const ADD_NEW_CONTACT_REQUEST = 'ADD_NEW_CONTACT_REQUEST';
export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS';
export const ADD_NEW_CONTACT_FAILURE = 'ADD_NEW_CONTACT_FAILURE';
export const DELETE_CONTACT_REQUEST = 'DELETE_CONTACT_REQUEST';
export const DELETE_CONTACT_SUCCESS = 'DELETE_CONTACT_SUCCESS';
export const DELETE_CONTACT_FAILURE = 'DELETE_CONTACT_FAILURE';
export const UPDATE_CONTACT_REQUEST = 'UPDATE_CONTACT_REQUEST';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILURE = 'UPDATE_CONTACT_FAILURE';
export const FETCH_ALL_CONTACTS_REQUEST = "FETCH_ALL_CONTACTS_REQUEST";
export const FETCH_ALL_CONTACTS_SUCCESS = "FETCH_ALL_CONTACTS_SUCCESS";
export const FETCH_ALL_CONTACTS_FAILURE = "FETCH_ALL_CONTACTS_FAILURE";

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MENU = 'CLOSE_MENU';


